### ISSUE TITLE
Deprecation warning: moment construction falls back to js Date.

### ISSUE THREAD

**Issue by dfoxxdfoxx** [fullcalendar/fullcalendar#3026]
When fullcalendar is loaded i am getting the below error in the Console.
If i look at the last few lines it looks to be referencing to the fullcalendar files:

`Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to http://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (http://mysite.com/agenda/calender/lib/moment.min.js:6:7124)
    at ea (http://mysite.com/agenda/calender/lib/moment.min.js:6:7827)
    at ya (http://mysite.com/agenda/calender/lib/moment.min.js:6:11660)
    at xa (http://mysite.com/agenda/calender/lib/moment.min.js:6:11530)
    at wa (http://mysite.com/agenda/calender/lib/moment.min.js:6:11251)
    at za (http://mysite.com/agenda/calender/lib/moment.min.js:6:11973)
    at Aa (http://mysite.com/agenda/calender/lib/moment.min.js:6:12007)
    at a (http://mysite.com/agenda/calender/lib/moment.min.js:6:202)
    at makeMoment (http://mysite.com/agenda/calender/fullcalendar.js:1069:17)
    at FC.moment (http://mysite.com/agenda/calender/fullcalendar.js:1000:9)`

**Comment by arshaw** [comment]
can you post a JSBin? http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by cah-danmonroe** [comment]
I also have this deprecation.  From this line in the initCurrentDate function.

`this.currentDate = this.moment(defaultDateInput).stripZone();`

**Comment by arshaw** [comment]
would love a recreation to know what yall's `defaultDate` setting is

**Comment by cah-danmonroe** [comment]
fullcalendar is a dependency of the Ember addon "ember-fullcalendar" which our product uses. ( https://github.com/scoutforpets/ember-fullcalendar ) I don't think it sets defaultDate
