### ISSUE TITLE
Need Help with: TypeError: (seg1.event.title || "").localeCompare is not a function

### ISSUE THREAD

**Issue by Weestdudochnicht** [fullcalendar/fullcalendar#3490]
Hey Guys,

I believe my Problem is not really a bug, becouse no one else post it as an issue.

My Problem:
I try to Update a event with the  `$('#mainCal').fullCalendar('updateEvent',` $scope.selectedEvent);`

It works for the most time, but sometimes it fails with the following console error:

angular.js:14199 TypeError: (seg1.event.title || "").localeCompare is not a function
    at compareSegs (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:4442:28)
    at Array.sort (native)
    at constructor.buildSegLevels (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:5223:8)
    at constructor.renderSegRow (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:5129:24)
    at constructor.renderSegRows (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:5058:10)
    at constructor.renderFgSegs (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:5019:39)
    at constructor.renderEvents (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:3518:17)
    at renderEvents (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:10345:16)
    at displayEvents (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:7103:8)
    at renderEvents (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:8214:16)(anonymous function) @ angular.js:14199(anonymous function) @ angular.js:10707$apply @ angular.js:18099(anonymous function) @ angular.js:26597dispatch @ jquery.js:4435elemData.handle @ jquery.js:4121

angular.js:14199 TypeError: (seg1.event.title || "").localeCompare is not a function
    at compareSegs (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:4442:28)
    at Array.sort (native)
    at constructor.buildSegLevels (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:5223:8)
    at constructor.renderSegRow (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:5129:24)
    at constructor.renderSegRows (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:5058:10)
    at constructor.renderFgSegs (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:5019:39)
    at constructor.renderEvents (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:3518:17)
    at renderEvents (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:10345:16)
    at displayEvents (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:7103:8)
    at renderEvents (http://localhost:3000/plugins/fullcalendar/dist/fullcalendar.js:8214:16)

my Event looks like: 
_allDay:true
_end:null
_id:"563696927"
_start:Moment
allDay:true
className:Array[2]
description:Array[1]
end:null
endDate:""
endTime:""
id:563696927
source:Object
start:Moment
startDate:Mon Jan 09 2017 00:00:00 GMT+0100 (CET)
startTime:Mon Jan 09 2017 00:00:00 GMT+0100 (CET)
title:Array[1]
__proto__:Object

U got any hints for me? i rly dont know what i did wrong there

**Comment by espen** [comment]
Try asking on [StackOverflow](http://stackoverflow.com). See https://fullcalendar.io/support/

Looks like your [title](https://fullcalendar.io/docs/event_data/Event_Object/) is an array instead of a string though.

**Comment by arshaw** [comment]
If you're stilling having an issue....

Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
