### ISSUE TITLE
v5 npm build system broken (yarn works fine)

### ISSUE THREAD

**Issue by BoLaMN** [fullcalendar/fullcalendar#5504]
v5 build system seems abit more difficult to build getting a few errors 

```
git clone --recursive git://github.com/fullcalendar/fullcalendar.git
npm install 
npm run-script build 
```

```
[16:25:58] Using gulpfile ~/Documents/fullcalendar/gulpfile.js
[16:25:58] Starting 'build'...
[16:25:58] Starting 'rm'...
[16:25:58] Finished 'rm' after 12 ms
[16:25:58] Starting 'ln'...
ln: node_modules/@fullcalendar/angular: No such file or directory
```

if i manually install @fullcalendar/angular i then get 

```
[16:30:56] Using gulpfile ~/Documents/fullcalendar/gulpfile.js
[16:30:56] Starting 'build'...
[16:30:56] Starting 'rm'...
rm: node_modules/@fullcalendar/angular: is a directory
```
if i modify the rm command with `rm -fr` i get a little further but on build it completely errors out 

```
nathan@macbook-pro fullcalendar % npm run-script build

> fullcalendar@5.0.0-rc build /Users/nathan/Documents/fullcalendar
> gulp build

[16:33:06] Using gulpfile ~/Documents/fullcalendar/gulpfile.js
[16:33:06] Starting 'build'...
[16:33:06] Starting 'rm'...
[16:33:06] Finished 'rm' after 15 ms
[16:33:06] Starting 'ln'...
[16:33:06] Finished 'ln' after 14 ms
[16:33:06] Starting 'rm'...
[16:33:06] Finished 'rm' after 14 ms
[16:33:06] Starting 'ln'...
[16:33:06] Finished 'ln' after 12 ms
[16:33:06] Starting 'linkVDomLib'...
[16:33:06] Finished 'linkVDomLib' after 6.82 ms
[16:33:06] Starting 'removeTscDevLinks'...
[16:33:06] Finished 'removeTscDevLinks' after 107 ms
[16:33:06] Starting 'writeTscDevLinks'...
[16:33:06] Finished 'writeTscDevLinks' after 340 ms
[16:33:06] Starting 'localesAllSrc'...
[16:33:06] Finished 'localesAllSrc' after 24 ms
[16:33:06] Starting 'tsc'...
[4:33:07 pm] Projects in this build:
    * packages/core-vdom/tsconfig.json
    * packages/common/tsconfig.json
    * packages/core/tsconfig.json
    * packages/interaction/tsconfig.json
    * packages/daygrid/tsconfig.json
    * packages/timegrid/tsconfig.json
    * packages/list/tsconfig.json
    * packages/bootstrap/tsconfig.json
    * packages/google-calendar/tsconfig.json
    * packages/luxon/tsconfig.json
    * packages/moment/tsconfig.json
    * packages/moment-timezone/tsconfig.json
    * packages/rrule/tsconfig.json
    * packages/__tests__/tsconfig.json
    * packages/bundle/tsconfig.json
    * packages-premium/premium-common/tsconfig.json
    * packages-premium/scrollgrid/tsconfig.json
    * packages-premium/timeline/tsconfig.json
    * packages-premium/resource-common/tsconfig.json
    * packages-premium/resource-daygrid/tsconfig.json
    * packages-premium/resource-timegrid/tsconfig.json
    * packages-premium/resource-timeline/tsconfig.json
    * packages-premium/__tests__/tsconfig.json
    * packages-premium/adaptive/tsconfig.json
    * packages-premium/bundle/tsconfig.json
    * tsconfig.json

[4:33:07 pm] Project 'packages/core-vdom/tsconfig.json' is out of date because output file 'packages/core-vdom/tsc/vdom.js' does not exist

[4:33:07 pm] Building project '/Users/nathan/Documents/fullcalendar/packages/core-vdom/tsconfig.json'...

packages/core-vdom/src/vdom.ts:1:25 - error TS2307: Cannot find module 'preact' or its corresponding type declarations.

1 import * as preact from 'preact'
                          ~~~~~~~~

packages/core-vdom/src/vdom.ts:25:1 - error TS2740: Type '{ Component: any; createElement: any; render: any; createRef: any; Fragment: any; createContext: <T>(defaultValue: T) => any; flushToDom: () => void; }' is missing the following properties from type 'typeof FullCalendarVDom': Ref, RefObject, ComponentType, Context, and 2 more.

25 window.FullCalendarVDom = {
   ~~~~~~~~~~~~~~~~~~~~~~~

packages/core-vdom/src/vdom.ts:61:30 - error TS2339: Property 'setState' does not exist on type 'FakeComponent'.

61   componentDidMount() { this.setState({}) }
                                ~~~~~~~~

[4:33:10 pm] Project 'packages/common/tsconfig.json' can't be built because its dependency 'packages/core-vdom' has errors

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/common/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/core-vdom' has errors

[4:33:10 pm] Project 'packages/core/tsconfig.json' can't be built because its dependency 'packages/core-vdom' has errors

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/core/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/core-vdom' has errors

[4:33:10 pm] Project 'packages/interaction/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/interaction/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages/daygrid/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/daygrid/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages/timegrid/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/timegrid/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages/list/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/list/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages/bootstrap/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/bootstrap/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages/google-calendar/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/google-calendar/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages/luxon/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/luxon/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages/moment/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/moment/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages/moment-timezone/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/moment-timezone/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages/rrule/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/rrule/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages/__tests__/tsconfig.json' can't be built because its dependency 'packages/core' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/__tests__/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/core' was not built

[4:33:10 pm] Project 'packages/bundle/tsconfig.json' can't be built because its dependency 'packages/core' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages/bundle/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/core' was not built

[4:33:10 pm] Project 'packages-premium/premium-common/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages-premium/premium-common/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages-premium/scrollgrid/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages-premium/scrollgrid/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages-premium/timeline/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages-premium/timeline/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages-premium/resource-common/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages-premium/resource-common/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages-premium/resource-daygrid/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages-premium/resource-daygrid/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages-premium/resource-timegrid/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages-premium/resource-timegrid/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages-premium/resource-timeline/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages-premium/resource-timeline/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages-premium/__tests__/tsconfig.json' can't be built because its dependency 'packages/__tests__' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages-premium/__tests__/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/__tests__' was not built

[4:33:10 pm] Project 'packages-premium/adaptive/tsconfig.json' can't be built because its dependency 'packages/common' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages-premium/adaptive/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/common' was not built

[4:33:10 pm] Project 'packages-premium/bundle/tsconfig.json' can't be built because its dependency 'packages/core' was not built

[4:33:10 pm] Skipping build of project '/Users/nathan/Documents/fullcalendar/packages-premium/bundle/tsconfig.json' because its dependency '/Users/nathan/Documents/fullcalendar/packages/core' was not built


Found 3 errors.

[16:33:10] 'tsc' errored after 3.63 s
[16:33:10] Error: shell command failed
    at ChildProcess.<anonymous> (/Users/nathan/Documents/fullcalendar/scripts/lib/shell.js:35:29)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:547:15)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
[16:33:10] 'build' errored after 4.17 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fullcalendar@5.0.0-rc build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fullcalendar@5.0.0-rc build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nathan/.npm/_logs/2020-06-17T07_03_10_611Z-debug.log```

**Comment by arshaw** [comment]
sorry about the troubles. the new build system actually requires yarn instead of npm.  i plan to document this and add more checks ASAP

**Comment by BoLaMN** [comment]
i should of looked at the scripts/ci.sh file and saw it required yarn, can confirm using yarn it built fine. 

```
brew install yarn
yarn install 
yarn run build
```

ill change the title to include `building with npm`

the CONTRIBUTING.md will need to be updated for the v5 release

**Comment by OttawaIan** [comment]
Is there a particular yarn version we should be using ?  I am having no luck trying to install fullcalendar using yarn

yarn --version
2.3.3

when I do a yarn install I get the following error:
 YN0013: │ hard-rejection@npm:2.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ has-ansi@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ has-ansi@npm:2.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ has-binary2@npm:1.0.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ has-cors@npm:1.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ fsevents@patch:fsevents@npm%3A2.3.2#builtin<compat/fsevents>::version=2.3.2&hash=127e8e: Cannot apply hunk #1 (set enableInlineHunks for details)
➤ YN0013: │ yn@npm:2.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zone.js@npm:0.10.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zwitch@npm:1.0.5 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 23s 961ms
➤ YN0000: Failed with errors in 47s 575ms

**Comment by arshaw** [comment]
@OttawaIan , i'm not sure why you're getting that error. that looks like a fine version number. the yarn version should theoretically be whatever fullcalendar needs... yarn v2 defers to what the repo says.

FYI, in master, the code now checks to make sure Yarn is being run instead of NPM.
