### ISSUE TITLE
Unable to run Jest test -  Cannot use import statement outside a module

### ISSUE THREAD

**Issue by qweluke** [fullcalendar/fullcalendar#5570]
With latest v5.1.0 I am unable to run Jet tests.

```
    /Volumes/workdata/projects/fr/front/node_modules/@fullcalendar/react/dist/main.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { __assign, __extends } from "tslib";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import OverlayLoader from './OverlayLoader';
      3 | import PropTypes from 'prop-types';
    > 4 | import FullCalendar from '@fullcalendar/react';
        | ^
      5 | import dayGridPlugin from '@fullcalendar/daygrid';
      6 | import listPlugin from '@fullcalendar/list';
      7 | import moment from 'moment';

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/components/RescuesSchedule.jsx:4:1)
```

I am using react-scripts (without ejecting). Is there any solution to get rid of this error?

**Comment by arshaw** [comment]
my explanation on this comment addresses this: https://github.com/fullcalendar/fullcalendar/issues/5467#issuecomment-649814949

**Comment by qweluke** [comment]
I've ended up with mocking fullcalendar like this

```
jest.mock('@fullcalendar/react', () => () => <div />);
jest.mock('@fullcalendar/daygrid', () => jest.fn());
jest.mock('@fullcalendar/list', () => jest.fn());
```

Note that this will prevent fullcalendar for being rendered but test should be working fine ;-)

**Comment by marcobeltempo** [comment]
Without mocking you can use `transformIgnorePatterns` to transpile fullcalendar

```js
// jest.config.js
module.exports = {
    transform: {
        '^.+\\.[t|j]sx?$': 'babel-jest'
    },
    moduleNameMapper: {
        '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
    },
    transformIgnorePatterns: [
        '/node_modules/(?!@fullcalendar/*).+\\.[t|j]sx?$'
    ],
};
```

**Comment by baileyandy** [comment]
I used the solution from @marcobeltempo but I also had to switch from `.babelrc` to `babel.config.js` since my project is using Babel 7 (see https://github.com/facebook/jest/issues/7578#issuecomment-451671656)
