### ISSUE TITLE
"Maximum update depth exceeded" error after resizing many times in Chrome

### ISSUE THREAD

**Issue by topched** [fullcalendar/fullcalendar#5606]
**Bug report**

When resizing the window many times in a row react crashes because the maximum update depth is exceeded.

Here is a link to a simple repro example - https://codesandbox.io/s/modest-forest-qhv3j?file=/src/App.js

Steps to reproduce:
1. Click the open new window button
2. In that newly opened window click on one of the corners and drag it around a whole bunch

Notice how it crashes after a few seconds. The window resize event should probably be debounced to handle this.

**Comment by arshaw** [comment]
hmmm, it actually is debounced already. I tried to drag it around a lot like you said but I can't get it to freeze.

maybe your problem is related to this other issue (which I'm also having trouble reproducing): https://github.com/fullcalendar/fullcalendar/issues/5558

**Comment by topched** [comment]
That's interesting you were not able to repo it. It could be chrome related, though I am unsure its related to the other issue because it does load properly initially.

**Comment by topched** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1463538/87343697-246dbf00-c502-11ea-8dee-01a894cc33a8.gif)

**Comment by acerix** [comment]
Thanks, confirmed, I get the same error in Chrome but could not reproduce the error in Firefox.  I had to periodically hold still while dragging to allow for the calendar to actually resize (due to debouncing) and get the error after about 20 resizes.

`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

**Comment by topched** [comment]
Do you have a rough estimate of when we can expect this to be fixed? We are looking to purchase fullcalendar, but this is currently a blocker for us.

**Comment by arshaw** [comment]
I actually reproduce this immediately when the browser pane starts out at 810 x 660

I think the height is oscillating, turning the page scrollbars on/off repeatedly. I though I guarded against this.

I'll fix very soon

**Comment by Anuj-786** [comment]
I am using V5.3.1 but still getting issue.

**Comment by rrozanka** [comment]
We are using `5.3.1` and we are able to reproduce it on Chrome. Please note that on OS X you will have to *enable* the scrollbars to reproduce. In our case it is happening when calendar is within `<div>` with a vertical scrollbar (not always). I guess the scrollbar is jumping between visible / non-visible states causes the calendar to recalculate sizes.

**Comment by ezze** [comment]
We have the issue in 5.11.3. Here is the call stack:

```
react-dom.development.js:23803 Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:23803:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21835:1)
    at Object.enqueueSetState (react-dom.development.js:12467:1)
    at Component.setState (react.development.js:365:1)
    at TableRow.updateSizing (TableRow.tsx:320:1)
    at TableRow.componentDidUpdate (TableRow.tsx:165:1)
    at commitLifeCycles (react-dom.development.js:20684:1)
    at commitLayoutEffects (react-dom.development.js:23426:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
checkForNestedUpdates @ react-dom.development.js:23803
scheduleUpdateOnFiber @ react-dom.development.js:21835
enqueueSetState @ react-dom.development.js:12467
Component.setState @ react.development.js:365
TableRow.updateSizing @ TableRow.tsx:320
TableRow.componentDidUpdate @ TableRow.tsx:165
commitLifeCycles @ react-dom.development.js:20684
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
enqueueSetState @ react-dom.development.js:12467
Component.setState @ react.development.js:365
PureComponent.safeSetState @ vdom-util.tsx:33
SimpleScrollGrid._this.handleSizing @ SimpleScrollGrid.tsx:196
Emitter.trigger @ Emitter.ts:34
(anonymous) @ CalendarContent.tsx:246
DelayedRunner.drained @ DelayedRunner.ts:88
DelayedRunner.tryDrain @ DelayedRunner.ts:66
setTimeout (async)
DelayedRunner.request @ DelayedRunner.ts:21
CalendarContent._this.handleWindowResize @ CalendarContent.tsx:257
react-dom.development.js:20085 The above error occurred in the <TableRow> component:

    at TableRow (http://localhost:3000/static/js/bundle.js:167830:43)
    at tbody
    at table
    at NowTimer (http://localhost:3000/static/js/bundle.js:164904:24)
    at div
    at Table (http://localhost:3000/static/js/bundle.js:168151:43)
    at DayTable (http://localhost:3000/static/js/bundle.js:168344:43)
    at div
    at Scroller (http://localhost:3000/static/js/bundle.js:165671:43)
    at div
    at td
    at tr
    at tbody
    at table
    at SimpleScrollGrid (http://localhost:3000/static/js/bundle.js:166004:43)
    at div
    at MountHook (http://localhost:3000/static/js/bundle.js:161272:43)
    at ViewRoot (http://localhost:3000/static/js/bundle.js:161349:43)
    at DayTableView (http://localhost:3000/static/js/bundle.js:168384:43)
    at div
    at ViewContainer (http://localhost:3000/static/js/bundle.js:164287:43)
    at CalendarContent (http://localhost:3000/static/js/bundle.js:164479:43)
    at div
    at CalendarRoot (http://localhost:3000/static/js/bundle.js:164692:43)
    at CalendarDataProvider (http://localhost:3000/static/js/bundle.js:163680:24)
    at FullCalendar (http://localhost:3000/static/js/bundle.js:172065:43)
    at div
    at div
    at observerComponent (http://localhost:3000/static/js/bundle.js:318382:69)
    at observerComponent (http://localhost:3000/static/js/bundle.js:318382:69)
    at div
    at PageContent (http://localhost:3000/static/js/bundle.js:10025:5)
    at div
    at observerComponent (http://localhost:3000/static/js/bundle.js:318382:69)
    at observerComponent (http://localhost:3000/static/js/bundle.js:318382:69)
    at Outlet (http://localhost:3000/static/js/bundle.js:404354:26)
    at main
    at http://localhost:3000/static/js/bundle.js:209181:25
    at http://localhost:3000/static/js/bundle.js:209160:66
    at section
    at http://localhost:3000/static/js/bundle.js:209197:63
    at http://localhost:3000/static/js/bundle.js:209160:66
    at section
    at http://localhost:3000/static/js/bundle.js:209197:63
    at http://localhost:3000/static/js/bundle.js:209160:66
    at observerComponent (http://localhost:3000/static/js/bundle.js:318382:69)
    at Routes (http://localhost:3000/static/js/bundle.js:404446:5)
    at AudioPlayerProvider (http://localhost:3000/static/js/bundle.js:3298:5)
    at Router (http://localhost:3000/static/js/bundle.js:404379:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:403859:5)
    at t.QueryClientProvider (http://localhost:3000/static/js/bundle.js:186685:15)
    at e.PersistQueryClientProvider (http://localhost:3000/static/js/bundle.js:184538:15)
    at observerComponent (http://localhost:3000/static/js/bundle.js:318382:69)
    at observerComponent (http://localhost:3000/static/js/bundle.js:318382:69)
    at FormProvider (http://localhost:3000/static/js/bundle.js:334030:31)
    at LocaleProvider (http://localhost:3000/static/js/bundle.js:209864:90)
    at ProviderChildren (http://localhost:3000/static/js/bundle.js:203547:24)
    at LocaleReceiver (http://localhost:3000/static/js/bundle.js:209732:90)
    at ConfigProvider (http://localhost:3000/static/js/bundle.js:203662:13)
    at ErrorBoundary (http://localhost:3000/static/js/bundle.js:6008:5)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
overrideMethod @ react_devtools_backend.js:4012
logCapturedError @ react-dom.development.js:20085
update.payload @ react-dom.development.js:20133
getStateFromUpdate @ react-dom.development.js:12102
processUpdateQueue @ react-dom.development.js:12250
updateClassInstance @ react-dom.development.js:13013
updateClassComponent @ react-dom.development.js:17432
beginWork @ react-dom.development.js:19073
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
enqueueSetState @ react-dom.development.js:12467
Component.setState @ react.development.js:365
PureComponent.safeSetState @ vdom-util.tsx:33
SimpleScrollGrid._this.handleSizing @ SimpleScrollGrid.tsx:196
Emitter.trigger @ Emitter.ts:34
(anonymous) @ CalendarContent.tsx:246
DelayedRunner.drained @ DelayedRunner.ts:88
DelayedRunner.tryDrain @ DelayedRunner.ts:66
setTimeout (async)
DelayedRunner.request @ DelayedRunner.ts:21
CalendarContent._this.handleWindowResize @ CalendarContent.tsx:257
Show 1 more frame
error-boundary.tsx:20 Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:23803:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21835:1)
    at Object.enqueueSetState (react-dom.development.js:12467:1)
    at Component.setState (react.development.js:365:1)
    at TableRow.updateSizing (TableRow.tsx:320:1)
    at TableRow.componentDidUpdate (TableRow.tsx:165:1)
    at commitLifeCycles (react-dom.development.js:20684:1)
    at commitLayoutEffects (react-dom.development.js:23426:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1) 
```

**Comment by ezze** [comment]
@arshaw @acerix Could it be reopened, please?
