### ISSUE TITLE
Error "failed to create symbolic link 'node_modules/@fullcalendar/angular'" in standard build process

### ISSUE THREAD

**Issue by BruceRBowers** [fullcalendar/fullcalendar#5749]
This is a bug in the standard build process, but "I love FullCalendar".

Reproduction steps:
In a shell (I use bash or zsh on MacOS):
git clone --recursive https://github.com/fullcalendar/fullcalendar
cd fullcalendar
git submodule init
git submodule update
npm install
npm run build 

Expected behavior:  The build completes successfully.

Actual behavior:  The following error is displayed:

bbowers@dhcp-xx-xxx-xxx-xx fullcalendar % npm run build 

> fullcalendar@5.3.0 build /Users/bbowers/gitworkspaces/temp/fullcalendar
> gulp build

[13:16:58] Using gulpfile ~/gitworkspaces/temp/fullcalendar/gulpfile.js
[13:16:58] Starting 'build'...
[13:16:58] Starting 'rm'...
[13:16:58] Finished 'rm' after 22 ms
[13:16:58] Starting 'ln'...
ln: node_modules/@fullcalendar/angular: No such file or directory
[13:16:58] 'ln' errored after 11 ms
[13:16:58] Error: shell command failed
    at ChildProcess.<anonymous> (/Users/bbowers/gitworkspaces/temp/fullcalendar/scripts/lib/shell.js:35:29)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:498:23)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[13:16:58] 'build' errored after 38 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fullcalendar@5.3.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fullcalendar@5.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bbowers/.npm/_logs/2020-08-25T20_16_58_648Z-debug.log
bbowers@dhcp-xx-xxx-xxx-xx fullcalendar %

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5504
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
