### ISSUE TITLE
Building on Windows fails (tsc errored due to missing packages-premium files?)

### ISSUE THREAD

**Issue by baba43** [fullcalendar/fullcalendar#6775]
I have been trying to get this project to work on my Windows machine for days now. Unfortunately, it doesn't work with Cygwin, on a Linux VM or with "Ubuntu on Windows" (as explained in the Contribution Guide).

Under "Ubuntu on Windows" I run the following commands:

```
git clone --recursive https://github.com/fullcalendar/fullcalendar.git
yarn 
yarn build
```

And this is the ouput:

```
[10:17:13] Using gulpfile /var/tmp/fullcalendar/gulpfile.js
[10:17:13] Starting 'build'...
[10:17:13] Starting 'removeTscDevLinks'...
[10:17:13] Finished 'removeTscDevLinks' after 167 ms
[10:17:13] Starting 'writeTscDevLinks'...
[10:17:14] Finished 'writeTscDevLinks' after 520 ms
[10:17:14] Starting 'localesAllSrc'...
[10:17:14] Finished 'localesAllSrc' after 22 ms
[10:17:14] Starting 'tsc'...
[10:17:14 AM] Projects in this build:
    * packages/core-preact/tsconfig.json
    * packages/common/tsconfig.json
    * packages/core/tsconfig.json
    * packages/interaction/tsconfig.json
    * packages/icalendar/tsconfig.json
    * packages/daygrid/tsconfig.json
    * packages/timegrid/tsconfig.json
    * packages/list/tsconfig.json
    * packages/bootstrap/tsconfig.json
    * packages/bootstrap5/tsconfig.json
    * packages/luxon2/tsconfig.json
    * packages/google-calendar/tsconfig.json
    * packages/luxon/tsconfig.json
    * packages/moment/tsconfig.json
    * packages/moment-timezone/tsconfig.json
    * packages/rrule/tsconfig.json
    * packages/__tests__/tsconfig.json
    * packages/bundle/tsconfig.json
    * packages-premium/__tests__/tsconfig.json
    * packages-premium/bundle/tsconfig.json
    * packages-premium/resource-common/tsconfig.json
    * packages-premium/resource-daygrid/tsconfig.json
    * packages-premium/resource-timegrid/tsconfig.json
    * packages-premium/resource-timeline/tsconfig.json
    * packages-premium/scrollgrid/tsconfig.json
    * packages-premium/timeline/tsconfig.json
    * packages-premium/adaptive/tsconfig.json
    * tsconfig.json

[10:17:14 AM] Project 'packages/core-preact/tsconfig.json' is out of date because output file 'packages/core-preact/tsc/vdom.js' does not exist

[10:17:14 AM] Building project '/var/tmp/fullcalendar/packages/core-preact/tsconfig.json'...

[10:17:16 AM] Project 'packages/common/tsconfig.json' is out of date because output file 'packages/common/tsc/CalendarApi.js' does not exist

[10:17:16 AM] Building project '/var/tmp/fullcalendar/packages/common/tsconfig.json'...

[10:17:19 AM] Project 'packages/core/tsconfig.json' is out of date because output file 'packages/core/tsc/Calendar.js' does not exist

[10:17:19 AM] Building project '/var/tmp/fullcalendar/packages/core/tsconfig.json'...

[10:17:20 AM] Project 'packages/interaction/tsconfig.json' is out of date because output file 'packages/interaction/tsc/ElementScrollGeomCache.js' does not exist

[10:17:20 AM] Building project '/var/tmp/fullcalendar/packages/interaction/tsconfig.json'...

[10:17:21 AM] Project 'packages/icalendar/tsconfig.json' is out of date because output file 'packages/icalendar/tsc/main.global.js' does not exist

[10:17:21 AM] Building project '/var/tmp/fullcalendar/packages/icalendar/tsconfig.json'...

[10:17:21 AM] Project 'packages/daygrid/tsconfig.json' is out of date because output file 'packages/daygrid/tsc/DayTable.js' does not exist

[10:17:21 AM] Building project '/var/tmp/fullcalendar/packages/daygrid/tsconfig.json'...

[10:17:22 AM] Project 'packages/timegrid/tsconfig.json' is out of date because output file 'packages/timegrid/tsc/AllDaySplitter.js' does not exist

[10:17:22 AM] Building project '/var/tmp/fullcalendar/packages/timegrid/tsconfig.json'...

[10:17:23 AM] Project 'packages/list/tsconfig.json' is out of date because output file 'packages/list/tsc/ListView.js' does not exist

[10:17:23 AM] Building project '/var/tmp/fullcalendar/packages/list/tsconfig.json'...

[10:17:23 AM] Project 'packages/bootstrap/tsconfig.json' is out of date because output file 'packages/bootstrap/tsc/main.global.js' does not exist

[10:17:23 AM] Building project '/var/tmp/fullcalendar/packages/bootstrap/tsconfig.json'...

[10:17:24 AM] Project 'packages/bootstrap5/tsconfig.json' is out of date because output file 'packages/bootstrap5/tsc/main.global.js' does not exist

[10:17:24 AM] Building project '/var/tmp/fullcalendar/packages/bootstrap5/tsconfig.json'...

[10:17:24 AM] Project 'packages/luxon2/tsconfig.json' is out of date because output file 'packages/luxon2/tsc/main.global.js' does not exist

[10:17:24 AM] Building project '/var/tmp/fullcalendar/packages/luxon2/tsconfig.json'...

[10:17:25 AM] Project 'packages/google-calendar/tsconfig.json' is out of date because output file 'packages/google-calendar/tsc/event-source-declare.js' does not exist

[10:17:25 AM] Building project '/var/tmp/fullcalendar/packages/google-calendar/tsconfig.json'...

[10:17:25 AM] Project 'packages/luxon/tsconfig.json' is out of date because output file 'packages/luxon/tsc/main.global.js' does not exist

[10:17:25 AM] Building project '/var/tmp/fullcalendar/packages/luxon/tsconfig.json'...

[10:17:25 AM] Project 'packages/moment/tsconfig.json' is out of date because output file 'packages/moment/tsc/main.global.js' does not exist

[10:17:25 AM] Building project '/var/tmp/fullcalendar/packages/moment/tsconfig.json'...

[10:17:26 AM] Project 'packages/moment-timezone/tsconfig.json' is out of date because output file 'packages/moment-timezone/tsc/main.global.js' does not exist

[10:17:26 AM] Building project '/var/tmp/fullcalendar/packages/moment-timezone/tsconfig.json'...

[10:17:26 AM] Project 'packages/rrule/tsconfig.json' is out of date because output file 'packages/rrule/tsc/event-declare.js' does not exist

[10:17:26 AM] Building project '/var/tmp/fullcalendar/packages/rrule/tsconfig.json'...

[10:17:27 AM] Project 'packages/__tests__/tsconfig.json' is out of date because output file 'packages/__tests__/tsc/main.js' does not exist

[10:17:27 AM] Building project '/var/tmp/fullcalendar/packages/__tests__/tsconfig.json'...

[10:17:31 AM] Project 'packages/bundle/tsconfig.json' is out of date because output file 'packages/bundle/tsc/main.js' does not exist

[10:17:31 AM] Building project '/var/tmp/fullcalendar/packages/bundle/tsconfig.json'...

error TS5083: Cannot read file '/var/tmp/fullcalendar/packages-premium/__tests__/tsconfig.json'.

error TS5083: Cannot read file '/var/tmp/fullcalendar/packages-premium/bundle/tsconfig.json'.

error TS5083: Cannot read file '/var/tmp/fullcalendar/packages-premium/resource-common/tsconfig.json'.

error TS5083: Cannot read file '/var/tmp/fullcalendar/packages-premium/resource-daygrid/tsconfig.json'.

error TS5083: Cannot read file '/var/tmp/fullcalendar/packages-premium/resource-timegrid/tsconfig.json'.

error TS5083: Cannot read file '/var/tmp/fullcalendar/packages-premium/resource-timeline/tsconfig.json'.

error TS5083: Cannot read file '/var/tmp/fullcalendar/packages-premium/scrollgrid/tsconfig.json'.

error TS5083: Cannot read file '/var/tmp/fullcalendar/packages-premium/timeline/tsconfig.json'.

error TS5083: Cannot read file '/var/tmp/fullcalendar/packages-premium/adaptive/tsconfig.json'.


Found 9 errors.

[10:17:31] 'tsc' errored after 18 s
[10:17:31] Error: shell command failed
    at ChildProcess.<anonymous> (/var/tmp/fullcalendar/scripts/lib/shell.js:35:29)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:466:23)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[10:17:31] 'build' errored after 18 s
```

Can someone please help me and many other users that seem to have this kind of problems?

**Comment by pabzm** [comment]
I have the exact same problem, copying verbatim from CONTRIBUTING.md results in this error. Can someone give a hint, please?

**Comment by baba43** [comment]
> I have the exact same problem, copying verbatim from CONTRIBUTING.md results in this error. Can someone give a hint, please?

The issue here is not the build itself, but the installation of dependencies. Cloning from git like in the CONTRIBUTING guide doesn't work anymore (some dependencies are empty). I had to checkout the repo using SSH. Then it worked. Check the error messages when cloning and fix that, then the build works.
