### ISSUE TITLE
Support dash-name slot names, for use with script tags

### ISSUE THREAD

**Issue by lemmel** [fullcalendar/fullcalendar#7078]
Hi

following the closing of fullcalendar/fullcalendar-vue#185, the silence on [Stack](https://stackoverflow.com/questions/73136360/fullcalendar-vue3-and-vanilla-js-generate-exceptions), and the fact that it is either a bug or a feature (namely not available without using all webpack/etc mecanism) not advertised as such, I post a shorted example code of the wrong behaviour.

So when using only vanilla JS, there is no obvious way to make the library to run; here are the interresting parts and further below are available the errors and the full example demonstrating the problem.

- I use only regular JS (no webpack, npm, and so on), then I use the CDNs: 
    ```html
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/3.2.12/vue.global.min.js" integrity="sha512-CLrLddI89KM+4mefYP8PbruyeARQAoQVwajhryM9hwM5bAeEFdtBwk0Wy6A9HlVeXyszFtXqOzg1Qy/A+Fwglg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/main.min.css" integrity="sha256-5veQuRbWaECuYxwap/IOE/DAwNxgm4ikX7nrgsqYp88=" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/main.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/locales-all.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/vue3@5.11.1/dist/main.global.js" crossorigin="anonymous"></script>
    ```
- as I don't use webpack (etc), I start the project this way: 
    ```js
    const QApp = {
      el: '#q-app',
      data: function() {
        return {
          calendarOptions: {},
          currentEvents: []
        }
      },
      methods: {}
    }
    window.addEventListener('load', (event) => {
        const app = Vue.createApp(QApp)
        app.component('FullCalendar', FullCalendar)
        app.mount('#q-app')
    });
    ```
- and finally, here is the html:
    ```html
    <div id="q-app">
        <template>
            <full-calendar
            class='demo-app-calendar'
            :options='calendarOptions'
            >
                <template v-slot:eventContent='arg'>
                    <b>{{ arg.timeText }}</b>
                    <i>{{ arg.event.title }}</i>
                </template>
            </full-calendar>
        </template>
    </div>
    ```

I have already big projects using CDNs that mix several libraries, so at first I thought to simply use the regular [fullcalendar](https://github.com/fullcalendar/fullcalendar), but when I tried to customize the **eventContent** handler, the returned html that included some vue components aren't detected by **Vue**. That is the reason why I turned to **fullcalendar-vue**.

<html>
<br/>
<br/>
</html>

Has someone an idea of how I should do use this project ? Or perhaps how I can make Vue to detect the Components that are in the return of the **eventContent** handler with the regular [fullcalendar](https://github.com/fullcalendar/fullcalendar) ?

<html>
<br/>
<br/>
<br/>
<br/>
</html>

Full error stack:
```
vue.global.min.js:1 You are running a development build of Vue.
Make sure to use the production build (*.prod.js) when deploying for production.
vue.global.min.js:1 [Vue warn]: Property "__b" was accessed during render but is not defined on instance. 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 [Vue warn]: Property "type" was accessed during render but is not defined on instance. 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 [Vue warn]: Property "constructor" was accessed during render but is not defined on instance. 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 [Vue warn]: Property "type" was accessed during render but is not defined on instance. 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 [Vue warn]: Property "props" was accessed during render but is not defined on instance. 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 [Vue warn]: Property "type" was accessed during render but is not defined on instance. 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 [Vue warn]: Unhandled error during execution of render function 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'is')
    at j$2 (main.js:61:6988)
    at I$1 (main.js:61:6369)
    at m (main.js:61:2205)
    at I$1 (main.js:61:6186)
    at Proxy.N (main.js:61:8331)
    at mn (vue.global.min.js:1:18544)
    at _e.fn (vue.global.min.js:1:55566)
    at _e.run (vue.global.min.js:1:5996)
    at a (vue.global.min.js:1:55975)
    at I (vue.global.min.js:1:54056)
vue.global.min.js:1 [Vue warn]: Property "type" was accessed during render but is not defined on instance. 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 [Vue warn]: Property "props" was accessed during render but is not defined on instance. 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 [Vue warn]: Property "key" was accessed during render but is not defined on instance. 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 [Vue warn]: Property "key" was accessed during render but is not defined on instance. 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 [Vue warn]: Property "type" was accessed during render but is not defined on instance. 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 [Vue warn]: Property "props" was accessed during render but is not defined on instance. 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 [Vue warn]: Unhandled error during execution of render function 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
vue.global.min.js:1 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/vue-next 
  at <FullCalendar class="demo-app-calendar" options= Object > 
  at <App>
_i @ vue.global.min.js:1
main.js:61 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at slice (<anonymous>)
    at j$2 (main.js:61:7077)
    at I$1 (main.js:61:6369)
    at m (main.js:61:2205)
    at I$1 (main.js:61:6186)
    at Proxy.N (main.js:61:8331)
    at mn (vue.global.min.js:1:18544)
    at _e.fn (vue.global.min.js:1:55566)
    at _e.run (vue.global.min.js:1:5996)
    at xi (vue.global.min.js:1:75573)
```

And the full code demonstrating the problem:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>HTML5 : Hello World Example</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/3.2.12/vue.global.min.js" integrity="sha512-CLrLddI89KM+4mefYP8PbruyeARQAoQVwajhryM9hwM5bAeEFdtBwk0Wy6A9HlVeXyszFtXqOzg1Qy/A+Fwglg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/main.min.css" integrity="sha256-5veQuRbWaECuYxwap/IOE/DAwNxgm4ikX7nrgsqYp88=" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/main.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/locales-all.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/vue3@5.11.1/dist/main.global.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <div id="q-app">
            <template>
                <full-calendar
                class='demo-app-calendar'
                :options='calendarOptions'
                >
                    <template v-slot:eventContent='arg'>
                        <b>{{ arg.timeText }}</b>
                        <i>{{ arg.event.title }}</i>
                    </template>
                </full-calendar>
            </template>
        </div>
<script>

let todayStr = new Date().toISOString().replace(/T.*$/, '') // YYYY-MM-DD of today

var bar = null
const QApp = {
  el: '#q-app',
  data: function() {
    return {
      calendarOptions: {
        headerToolbar: {
          left: 'prev,next today',
          center: 'title',
          right: 'dayGridMonth,timeGridWeek,timeGridDay'
        },
        initialView: 'dayGridMonth',
        initialEvents: [
            {id: '54545454',title: 'All-day event',start: todayStr},
            {id: '98989898',title: 'Timed event',start: todayStr + 'T12:00:00'}
        ],
      }
    }
  },
  methods: {}
}
window.addEventListener('load', (event) => {
    const app = Vue.createApp(QApp)
    app.component('FullCalendar', FullCalendar)
    app.mount('#q-app')
});
</script>

</body>
</html>

```

**Comment by SwanValues** [comment]
I spent a lot of time on it.
@arshaw Has the problem been solved?
@lemmel I changed the 'eventContent' of the fullcalendar.js file to 'eventcontent', that can be fixed.

**Comment by lemmel** [comment]
@SwanValues I don't understand what you said; is it a question, a fact, something else ? 
Is it a solution ? If it is, then I don't understand it.

**Comment by SwanValues** [comment]
@lemmel sorry，my english is poor.
because case-sensitive attributes are not allow in HTML.  so v-slot:eventContent is interpreted as v-slot:eventcontent which fullcalendar doesn't know to look for.
fullcalendar looks for v-slot:eventContent with eventContent, so I've replaced all 'eventContent' in Fullcalendar.js with 'eventcontent'

**Comment by lemmel** [comment]
Ok, did that correct the problem ?

Even though it may seems to correct the behaviour, it may not be a "good solution" as 
- Fullcalendar must behave like any other vue library
- it may breaks something else

Futhermore, we should not alter the official Fullcalendar's code as it would mean that we will be forced to maintain my own version.   
If you think that the fix is good, then perhaps you could run the tests, and if it is really ok, submit a PR: https://github.com/fullcalendar/fullcalendar/blob/main/CONTRIBUTING.md

**Comment by arshaw** [comment]
I'll try to implement this fix for the new release
