### ISSUE TITLE
Style injection fails if FullCalendar v6 is mounted in iframe

### ISSUE THREAD

**Issue by rangermeier** [fullcalendar/fullcalendar#7301]
### Reduced Test Case

https://stackblitz.com/edit/github-w8g37h?file=src/DemoApp.vue

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

FullCalendar v6 fails to inject its CSS if the component is mounted inside an iframe but the JS is executed from the top level document.

The Reduced Test Case makes use of the Vue connector, but I reckon the mechanism for injecting CSS is independent of the framework used.

Error message on Chrome Dev Console:
```
[Vue warn]: Error in mounted hook: "HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': Only one element on document allowed."

found in

---> <FullCalendar>
       <IApp>
         <IFrame> at src/IFrame.vue
           <DemoApp> at src/DemoApp.vue
             <Root>
main.js:3897 DOMException: Failed to execute 'insertBefore' on 'Node': Only one element on document allowed.
    at injectStylesBefore (https://githubw8g37h-klqn--8080--bc9c2adb.local-credentialless.webcontainer.io/main.js:12251:26)
    at hydrateStylesRoot (https://githubw8g37h-klqn--8080--bc9c2adb.local-credentialless.webcontainer.io/main.js:12241:9)
    at registerStylesRoot (https://githubw8g37h-klqn--8080--bc9c2adb.local-credentialless.webcontainer.io/main.js:12236:9)
    at ensureElHasStyles (https://githubw8g37h-klqn--8080--bc9c2adb.local-credentialless.webcontainer.io/main.js:12227:5)
    at new Calendar (https://githubw8g37h-klqn--8080--bc9c2adb.local-credentialless.webcontainer.io/main.js:11869:64)
    at VueComponent.mounted (https://githubw8g37h-klqn--8080--bc9c2adb.local-credentialless.webcontainer.io/main.js:20760:26)
    at invokeWithErrorHandling (https://githubw8g37h-klqn--8080--bc9c2adb.local-credentialless.webcontainer.io/main.js:3865:61)
    at callHook$1 (https://githubw8g37h-klqn--8080--bc9c2adb.local-credentialless.webcontainer.io/main.js:4879:13)
    at Object.insert (https://githubw8g37h-klqn--8080--bc9c2adb.local-credentialless.webcontainer.io/main.js:5269:13)
    at invokeInsertHook (https://githubw8g37h-klqn--8080--bc9c2adb.local-credentialless.webcontainer.io/main.js:7784:38)
```

I think the issue is that in `@fullcalendar/core/internal-common.js:8` the CSS is injected once correctly in the top-level document when the script is loaded:
```
if (typeof document !== 'undefined') {
    registerStylesRoot(document, document.head, document.head.querySelector('script,link,style'));
}
```
When FullCalendar is mounted in a iframe, the `ensureElHasStyles(el)` function is called, but the `registerStylesRoot(rootNode, parentEl = rootNode, insertBefore = parentEl.firstChild)` function uses bad defaults for 
 `parentEl` and `insertBefore`.

**Comment by DanielHudson2** [comment]
Can this be picked up again? I'm experiencing this issue specifically in the context of a WordPress block in page editor as it gets rendered in an iframe, this bug completely stops the block from rendering
