### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'cssRules')

### ISSUE THREAD

**Issue by dotnetmael** [fullcalendar/fullcalendar#7428]
### Reduced Test Case

https://stackblitz.com/github/fullcalendar/fullcalendar-examples/tree/main/angular15?file=README.md

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

Hi,

I want to use SSR with FullCalendar in Angular but I got the following issue :

```
TypeError: Cannot read properties of undefined (reading 'cssRules')
    at appendStylesTo (/Users/dotnetmael/Documents/testSSr/fullcalendar-examples/angular15/dist/example/server/vendor.js:174626:25)
    at /Users/dotnetmael/Documents/testSSr/fullcalendar-examples/angular15/dist/example/server/vendor.js:174590:5
    at Map.forEach (<anonymous>)
    at injectStyles (/Users/dotnetmael/Documents/testSSr/fullcalendar-examples/angular15/dist/example/server/vendor.js:174589:12)
    at Module.88836 (/Users/dotnetmael/Documents/testSSr/fullcalendar-examples/angular15/dist/example/server/vendor.js:174663:1)
    at null.__webpack_require__ (../src/app/app.component.css:47:1)
    at Module.55354 (/Users/dotnetmael/Documents/testSSr/fullcalendar-examples/angular15/dist/example/server/vendor.js:172071:77)
    at null.__webpack_require__ (../src/app/app.component.css:47:1)
    at Module.42075 (/Users/dotnetmael/Documents/testSSr/fullcalendar-examples/angular15/dist/example/server/vendor.js:171308:76)
    at null.__webpack_require__ (../src/app/app.component.css:47:1)
```

To reproduce the issue : 

Clone the Angular 15 example repo
Add nguniversal/express-engine (`ng add @nguniversal/express-engine`)
Add domino for the server-side DOM (` npm install domino`)
Configure the server.ts file to this : 

```
import 'zone.js/node';

import { APP_BASE_HREF } from '@angular/common';
import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { existsSync } from 'fs';
import { join } from 'path';

const domino = require('domino');
const fs = require('fs');
const path = require('path');

// Use the browser index.html as template for the mock window
const template = fs
  .readFileSync(path.join(join(process.cwd(), 'dist/example/browser'), 'index.html'))
  .toString();

const window = domino.createWindow(template);
global['window'] = window;
global['document'] = window.document;
global['localStorage'] = window.localStorage;
global['navigator'] = window.navigator;
global['CSS'] = window.CSS;

import { AppServerModule } from './src/main.server';

// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/example/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';

  // Our Universal express-engine (found @ https://github.com/angular/universal/tree/main/modules/express-engine)
  server.engine('html', ngExpressEngine({
    bootstrap: AppServerModule,
  }));

  server.set('view engine', 'html');
  server.set('views', distFolder);

  // Example Express Rest API endpoints
  // server.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get('*.*', express.static(distFolder, {
    maxAge: '1y'
  }));

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });

  return server;
}

function run(): void {
  const port = process.env['PORT'] || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = mainModule && mainModule.filename || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}

export * from './src/main.server';
```

Add the commonJS module on tsconfig.server.json : 

```
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "outDir": "./out-tsc/server",
    "types": [
      "node"
    ],
    "module": "CommonJS"
  },
  "files": [
    "src/main.server.ts",
    "server.ts"
  ]
}
```

**Comment by dotnetmael** [comment]
I did a repo with the issue : https://github.com/dotnetmael/fullcalendar-issue

**Comment by Andrew-Zakharov** [comment]
Hello

Just to note: 

We use FullCalendar in our Jira app (inside iframe).
It was working fine until we start migration from Connect to Forge, then the same issue appeared.
Same resolution with version downgrade helped.

Our connector - React (we don't use SSR or any sort of server components).
