### ISSUE TITLE
v6.1.8 Not working with Salesforce LWC

### ISSUE THREAD

**Issue by andrew-cox-prophesion-com** [fullcalendar/fullcalendar#7439]
### Reduced Test Case

Description of Reduced Test Case provided below

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

**Reduced Test Case**
1. Get fullcalendar-6.1.8 and upload as a static resource into Salesforce org as fullCalendarV6
2. Turn on Lightning Web Security (in Settings -> Session Settings)
3. Setup LWC using fullcalendar as follows:

**Template:**
```
<template>
    <div class="slds-grid slds-wrap slds-theme_default">
        <div class="slds-col slds-size_9-of-12">    
            <!-- fullcalendar sits in this div -->
            <div id="calendar" class="fullcalendarjs"></div>
        </div>
    </div>
</template>
```
**Controller:**
```
import { LightningElement } from 'lwc';
import fullCalendarResource from '@salesforce/resourceUrl/fullCalendarV6';
import { loadScript } from 'lightning/platformResourceLoader';
import { ShowToastEvent } from 'lightning/platformShowToastEvent';

export default class FullCalendarV6 extends LightningElement {
    
    fullCalendarInitialized = false;
    
   /**
    * Load the fullcalendar.io in this lifecycle hook method
    */
    renderedCallback() {  

        if (this.fullCalendarInitialized) {
            return;
          }
          this.fullCalendarInitialized = true;
          
    // Executes all loadScript and loadStyle promises
    // and only resolves them once all promises are done
    Promise.all([
        loadScript(this, fullCalendarResource + '/fullcalendarV6/dist/index.global.js'),
      ])
        .then(() => {
          console.log("init");
          this.init();
        })
        .catch(error => {
          console.log("error", error);
          this.dispatchEvent(
            new ShowToastEvent({
              title: "Error loading FullCalendar",
              //message: error.message,
              variant: "error"
            })
          );
        });
    }
        
    init() {
        console.log(FullCalendar.version);
        console.log(FullCalendar.Calendar);
        
        var calendarEl = this.template.querySelector(".fullcalendarjs");

        // eslint-disable-next-line no-undef
        this.calendar = new FullCalendar.Calendar(calendarEl, {
          initialView: 'multiMonthYear'          
        });
        this.calendar.render();
    }    
}
```
4. The LWC will not work because the javascript explicity sets "use strict". (See https://developer.salesforce.com/docs/platform/lwc/guide/js-third-party-strict-mode.html) To fix for this, and to attach the fullCalendar to the global object the **initial** and **final** lines of the code need to be changed from:

Original _Initial Lines_
```
var FullCalendar = (function (exports) {

    'use strict';
```
Amended _Initial Lines_
```
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
    typeof define === 'function' && define.amd ? define(['exports'], factory) :
    (global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.FullCalendar = global.FullCalendar || {}));
    })(this, (function (exports) { 'use strict';
```
Original _final line_
```
})({});
```
Amended _final line_
```
}));
```
5. With these amendments in place the FullCalendar object is attached to the global variable but FullCalendar still hasn't been constructed properly! To remedy that I put try catch blocks around the fullCalendar code and found where it was failing

So Initial Lines become:
```
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
    typeof define === 'function' && define.amd ? define(['exports'], factory) :
    (global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.FullCalendar = global.FullCalendar || {}));
    })(this, (function (exports) { 'use strict';

    try {
```
And Final Lines:
```
        return exports;
    }
    catch (err) {
        console.log('Error');
        console.log(err);
    }
}));
```
6. When we do this we see the error as follows in the browser (Chrome) console:

> TypeError: Cannot read properties of undefined (reading 'error')
>     at apply (aura_prod.js:63:49064)
>     at Object.apply (aura_prod.js:41:4086)
>     at aura_prod.js:63:77513
>     at on.hybridGetTrap [as get] (eval at <anonymous> (aura_prod.js:63:89762), <anonymous>:3:20135)
>     at queryNonceValue (eval at <anonymous> (eval at <anonymous> (aura_prod.js:63:89762)), <anonymous>:96:36)
>     at getNonceValue (eval at <anonymous> (eval at <anonymous> (aura_prod.js:63:89762)), <anonymous>:75:37)
>     at registerStylesRoot (eval at <anonymous> (eval at <anonymous> (aura_prod.js:63:89762)), <anonymous>:41:35)
>     at eval (eval at <anonymous> (eval at <anonymous> (aura_prod.js:63:89762)), <anonymous>:108:13)
>     at eval (eval at <anonymous> (eval at <anonymous> (aura_prod.js:63:89762)), <anonymous>:8:80)
>     at eval (eval at <anonymous> (eval at <anonymous> (aura_prod.js:63:89762)), <anonymous>:9:7)

7. It appears (from further debugging) that the problem is that the script is seeking to retrieve the nonce and that Lightning Web Security is stopping that in some way. To deal with this I changed the code for queryNonceValue as follows:

Original queryNonceValue:
```
function queryNonceValue() {
            const metaWithNonce = document.querySelector('meta[name="csp-nonce"]');
            if (metaWithNonce && metaWithNonce.hasAttribute('content')) {
                return metaWithNonce.getAttribute('content');
            }
            const elWithNonce = document.querySelector('script[nonce]');
            if (elWithNonce) {
                return elWithNonce.nonce || '';
            }
            return '';
}
```
Amended queryNonceValue:
```        
function queryNonceValue() {
            try {
                const metaWithNonce = document.querySelector('meta[name="csp-nonce"]');
                if (metaWithNonce && metaWithNonce.hasAttribute('content')) {
                    return metaWithNonce.getAttribute('content');
                }
                const elWithNonce = document.querySelector('script[nonce]');
                console.log('elWithNonce');
                console.log(elWithNonce);
                if (elWithNonce) {
                    return elWithNonce.nonce || '';
                }
                return '';    
            }
            catch (err) {
                console.log('Error in queryNonceValue');
                console.log(err.message);
                console.log(err.stack);
            }
}
```

With this final amendment in place the fullcalendar LWC loads and displays.
I still get errors in the console which look like this 👇 but it works!
(I think the issue is something to do with not being able to access the nonce in javascript when Lightning Web Security is on.)

> Error in queryNonceValue
> VM16255:3 Cannot read properties of undefined (reading 'error')
> VM16255:3 TypeError: Cannot read properties of undefined (reading 'error')
>     at apply (aura_prod.js:63:49064)
>     at Object.apply (aura_prod.js:41:4086)
>     at aura_prod.js:63:77513
>     at on.hybridGetTrap [as get] (eval at <anonymous> (aura_prod.js:63:89762), <anonymous>:3:20135)
>     at queryNonceValue (eval at <anonymous> (eval at <anonymous> (aura_prod.js:63:89762)), <anonymous>:92:40)
>     at getNonceValue (eval at <anonymous> (eval at <anonymous> (aura_prod.js:63:89762)), <anonymous>:75:37)
>     at registerStylesRoot (eval at <anonymous> (eval at <anonymous> (aura_prod.js:63:89762)), <anonymous>:41:35)
>     at ensureElHasStyles (eval at <anonymous> (eval at <anonymous> (aura_prod.js:63:89762)), <anonymous>:31:17)
>     at new Calendar (eval at <anonymous> (eval at <anonymous> (aura_prod.js:63:89762)), <anonymous>:9726:21)
>     at Proxy.init (eval at <anonymous> (eval at <anonymous> (aura_prod.js:63:89762)), <anonymous>:1:795)

I'm raising this as a bug because there's a lot of amending that needs to be done to get this working and I don't know if my fix will cause other problems down the line. Not sure if the fullCalendar team can reach out to the Salesforce developers and find a way through?

**Comment by acerix** [comment]
Related to https://github.com/fullcalendar/fullcalendar/issues/6196

Also reported in https://fullcalendar.freshdesk.com/a/tickets/6997

**Comment by andrew-cox-prophesion-com** [comment]
Thanks Dylan.
I don’t have access to view the Freshdesk ticket.
Thanks,

Andrew

**Comment by arshaw** [comment]
Please see my recent comment about LWC support here: https://github.com/fullcalendar/fullcalendar/issues/6196#issuecomment-4271167959

In v7, `'use strict'` is still in the dist output (i might remove it) but it no longer causes problems with the UMD intro/outro, which is now purely IIFE (no more UMD). Please subscribe to #6196 for updates
