### ISSUE TITLE
Error Occurs When Using useContext in Custom View in FullCalendar

### ISSUE THREAD

**Issue by linkillhz** [fullcalendar/fullcalendar#7534]
### Reduced Test Case

https://stackblitz.com/edit/react-6ndg3d?file=src%2Ftest-view.js

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

When using React ^18.0.0 and FullCalendar ^6.1.9, an error occurs when utilizing the useContext hook within a custom view in FullCalendar.

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (react-dom.development.js:16227:9)
    at useContext (react.development.js:1619:21)
```

- The issue does not occur with FullCalendar version v5.11.5 (the latest in the 5.x series), but it appears upon upgrading to version 6.
- Commenting out the useContext part results in the custom view being displayed normally.

Could you please inform me whether this issue is a bug in FullCalendar itself, or if there is a problem with the way I am using it? 

Also, I would like to express my gratitude for providing such an excellent calendar solution. FullCalendar has been invaluable for our projects.

**Comment by acerix** [comment]
It sounds like this existing ticket may cover this:
https://github.com/fullcalendar/fullcalendar/issues/7448
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

If this is a different bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by linkillhz** [comment]
@acerix 
I'm not certain if it's the same issue, but it seems like it might be a different problem. 
Also, I have already provided a minimal runnable demonstration.

https://stackblitz.com/edit/react-6ndg3d?file=src%2Ftest-view.js

I would appreciate it if you could check it out. 
Thanks,

**Comment by acerix** [comment]
Sorry, I missed your test case.  And yes it seems like different error than in other issue so I'll reopen this.
