### ISSUE TITLE
`el.getRootNode is not a function` error when building with Angular 17 SSR

### ISSUE THREAD

**Issue by stehag** [fullcalendar/fullcalendar#7550]
### Reduced Test Case

https://github.com/stehag/fullcalendar-a17-ssr-bug

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [x] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

Fullcalendar with angular 17 SSR yields this error: 

ERROR TypeError: el.getRootNode is not a function
    at ensureElHasStyles (/Users/hag/angular/a17-fullcalendar/node_modules/@fullcalendar/core/internal-common.js:15:31)
    at Calendar (/Users/hag/angular/a17-fullcalendar/node_modules/@fullcalendar/core/index.js:2033:9)
    at FullCalendarComponent.ngAfterViewInit (/Users/hag/angular/a17-fullcalendar/node_modules/@fullcalendar/angular/fesm2020/fullcalendar-angular.mjs:407:38)
    at callHookInternal (/Users/hag/angular/a17-fullcalendar/node_modules/@angular/core/fesm2022/core.mjs:3523:14)
    at callHook (/Users/hag/angular/a17-fullcalendar/node_modules/@angular/core/fesm2022/core.mjs:3550:13)
    at callHooks (/Users/hag/angular/a17-fullcalendar/node_modules/@angular/core/fesm2022/core.mjs:3505:17)
    at executeInitAndCheckHooks (/Users/hag/angular/a17-fullcalendar/node_modules/@angular/core/fesm2022/core.mjs:3455:9)
    at refreshView (/Users/hag/angular/a17-fullcalendar/node_modules/@angular/core/fesm2022/core.mjs:13461:21)
    at detectChangesInView (/Users/hag/angular/a17-fullcalendar/node_modules/@angular/core/fesm2022/core.mjs:13615:9)
    at detectChangesInViewIfAttached (/Users/hag/angular/a17-fullcalendar/node_modules/@angular/core/fesm2022/core.mjs:13578:5)
    
    
To recreate from reduced test-case, clone repo, npm install, ng serve, access http://localhost:4200, check the terminal console.

**Comment by nuhrecep** [comment]
Do you have any information about the cause of this error?

**Comment by lbattaglioli2000** [comment]
I'm getting the same issue too. Using NPM install, and instantiating the calendar via Alpine JS. Calendar won't render.

**Comment by stehag** [comment]
Unfortunatley this occurs in preact as well, so i'll guess it will take some time to get support for Angular 17 ssr :(

**Comment by aravindh-imagine** [comment]
I'm getting the same issue but I have check isPlatformBrower.Then I don't have see this issue.
![image](https://github.com/fullcalendar/fullcalendar/assets/132185883/4cbd18a3-d7ae-499f-a510-d94e502e026f)
![image](https://github.com/fullcalendar/fullcalendar/assets/132185883/a8c20fb1-b870-4a03-84f9-e1d89cbb1d09)

**Comment by arshaw** [comment]
There's a workaround I'll try to release today or tomorrow. Apologies for the troubles.

**Comment by arshaw** [comment]
I've released a fix in [v6.1.11](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.11)

Could someone please verify?
