### ISSUE TITLE
Maximum call stack size exceeded at DayGridSegHierarchy.splitEntry

### ISSUE THREAD

**Issue by zzbrglezz** [fullcalendar/fullcalendar#7556]
### Reduced Test Case

/

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

When user opens calendar, i get error:
```
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at DayGridSegHierarchy.splitEntry (internal-common.js:5792:1)
    at DayGridSegHierarchy.handleInvalidInsertion (internal-common.js:5774:1)
    at DayGridSegHierarchy.handleInvalidInsertion (internal.js:414:1)
    at DayGridSegHierarchy.insertEntry (internal-common.js:5765:1)
    at DayGridSegHierarchy.splitEntry (internal-common.js:5792:1)
    at DayGridSegHierarchy.handleInvalidInsertion (internal-common.js:5774:1)
    at DayGridSegHierarchy.handleInvalidInsertion (internal.js:414:1)
    at DayGridSegHierarchy.insertEntry (internal-common.js:5765:1)
    at DayGridSegHierarchy.splitEntry (internal-common.js:5792:1)
    at DayGridSegHierarchy.handleInvalidInsertion (internal-common.js:5774:1)
    at DayGridSegHierarchy.handleInvalidInsertion (internal.js:414:1)
    at DayGridSegHierarchy.insertEntry (internal-common.js:5765:1)
    at DayGridSegHierarchy.splitEntry (internal-common.js:5792:1)
    at DayGridSegHierarchy.handleInvalidInsertion (internal-common.js:5774:1)
    at DayGridSegHierarchy.handleInvalidInsertion (internal.js:414:1)
    at DayGridSegHierarchy.insertEntry (internal-common.js:5765:1)
```
and it causes calendar to freeze.

**Comment by taylorTianzige** [comment]
i have the same issue. help~~~

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by taylorTianzige** [comment]
here is the demostration of those events, in our project, this bug will occurs when i jump to May, i inspection the events data, i dont think the data have problem, i also set the data as a static vars, this bug still happened, the length of data just 47, i test it in this demonstration, it not happen either, so please help. https://stackblitz.com/edit/github-l5uyfh?file=src%2Fevent-utils.js

**Comment by taylorTianzige** [comment]
![1703141146881](https://github.com/fullcalendar/fullcalendar/assets/148300356/baa61313-5e4e-4740-aae2-1f2120e46091)

**Comment by taylorTianzige** [comment]
datesSet={this.handleDatesChange}  i was set this function to fetch events when current date change, is this behavior will  cause this bug?

**Comment by taylorTianzige** [comment]
i just tested it, this bug just simply happened when change the date by click the right arrow button. i not sure its caused by events data or the fullcalendar or something else.

**Comment by zzbrglezz** [comment]
@taylorTianzige If you use **dayMaxEventRows** change it to **dayMaxEvents**. That fixed bug for me now.

**Comment by taylorTianzige** [comment]
> @taylorTianzige If you use **dayMaxEventRows** change it to **dayMaxEvents**. That fixed bug for me now.

i tried, doesn't work for me.

**Comment by taylorTianzige** [comment]
@acerix help~~

**Comment by YuvalLevi5** [comment]
> @taylorTianzige If you use **dayMaxEventRows** change it to **dayMaxEvents**. That fixed bug for me now.

This worked for me too
