### ISSUE TITLE
[v7-beta] scrollgrid plugin not included for resource-timeline

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#7783]
### Reduced Test Case

https://stackblitz.com/edit/github-ttxgzn?file=package.json,src%2FDemoApp.jsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

```
Uncaught RangeError: Must import @fullcalendar/scrollgrid
    at getScrollerSyncerClass (index.js:54641:15)
    at ResourceTimelineView.componentDidMount (index.js:60209:98)
    at index.js:3445:7360
    at Array.some (<anonymous>)
    at index.js:3445:7341
    at Array.some (<anonymous>)
    at j (index.js:3445:7301)
    at B (index.js:3445:9617)
    at index.js:47707:67
    at flushSync (index.js:50270:5)
```

**Comment by arshaw** [comment]
TODO: check for other views that use getScrollerSyncerClass and other scrollgrid utils

**Comment by arshaw** [comment]
Works now in [v7.0.0-beta.1](https://github.com/fullcalendar/fullcalendar-workspace/releases/tag/v7.0.0-beta.1)
Repro: https://stackblitz.com/edit/github-ttxgzn?file=package.json,src%2FDemoApp.jsx
