### ISSUE TITLE
[v7-beta] coordRes is not iterable

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#7784]
### Reduced Test Case

https://stackblitz.com/edit/github-ttxgzn-eswhgr?file=package.json,src%2FDemoApp.jsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

Revealed after I made a workaround for #7783

Happens when no resources. Probably in other scenarios too, when resources/groups don't span entire height

```
Uncaught TypeError: coordRes is not iterable
    at ResourceTimelineView.queryEntityScroll (index.js:60264:41)
    at ResourceTimelineView.getSnapshotBeforeUpdate (index.js:60221:21)
    at O (index.js:3447:6735)
    at S (index.js:3447:1865)
    at z (index.js:3447:8503)
    at O (index.js:3447:7157)
    at S (index.js:3447:1865)
    at O (index.js:3447:6765)
    at S (index.js:3447:1865)
    at O (index.js:3447:6765)
```

**Comment by arshaw** [comment]
Works now in [v7.0.0-beta.1](https://github.com/fullcalendar/fullcalendar-workspace/releases/tag/v7.0.0-beta.1)
Repro: https://stackblitz.com/edit/github-ttxgzn?file=package.json,src%2FDemoApp.jsx
